### ISSUE TITLE
Difficulty in installation

### ISSUE THREAD

**Issue by shruti927** [maribelacosta/wikiwho#8]
While installing wikiwho I got the following error:
File "C:\Python34\WikiwhoRelationships.py", line 14, in <module>
    from structures import Text
ImportError: No module named 'structures'

**Comment by wikiwho** [comment]
hi, to narrow down the error source:  did you download all corresponding folders and named the folders “etc” and “structures”  as in our master branch?

**Comment by shruti927** [comment]
No, I just ran the wikiwhorelationships.py file. Do I have to run the files in etc and structures folders or is there any other way to do the same?

**Comment by wikiwho** [comment]
You just have to download all the files and subfolders and put/unzip them them into the same directory. Then run the WikiwhoRelationships.py - or, if you really only need authorship, the Wikiwho.py.

**Comment by shruti927** [comment]
I did the same but still got the above error.

**Comment by jsalsman** [comment]
Hi Fabian, Shruti is helping with the accuracy review project, so needs
dates more than authorship.

Shruti, please _document the steps you used to create a PythonAnywhere
account, and the resulting Python source files and subdirectories (as much
of the folder structure as you can easily obtain, except for large parts
you believe were installed by PythonAnywhere instead of your work --
include the folders for those, but not the files.) The steps should be
sufficient for someone else to reproduce the same problem, and you should
try them again to make sure they do reproduce the problem using another
account.  If your steps do reproduce the problem, then include the error
messages produced with any differences between the two._

Please add that information here and on:
https://etherpad.wikimedia.org/p/accuracyreview

Thank you both!

**Comment by wikiwho** [comment]
hi, so what Python version are you actually using? if you are using the python 2.7 version from the master branch,  did you use the wmf utilities from here: https://bitbucket.org/halfak/wikimedia-utilities/get/2cf1f506e336.zip  and install them or put them into the same folder?

**Comment by jsalsman** [comment]
Fabian, this may have been my fault for suggesting
https://github.com/maribelacosta/wikiwho/tree/python3
with https://github.com/mediawiki-utilities/python-mediawiki-utilities
but I was very hopeful that it would be okay because mediawiki-utilities is
only being maintained in Python 3. I should have asked you or suggested the
Python 2.7 version first.

**Comment by wikiwho** [comment]
I just suggested the way to run it for 2.7, but it works fine as well with python 3. I just tested it with our python3 branch, python 3.4 and the up-to-date mediawiki-utilities and it runs without hiccups. So I'm not sure what the issue is on your side.

**Comment by shruti927** [comment]
I am using Python 3 on Windows 8.1.Should I send the screenshots and mention the steps I tried?

**Comment by wikiwho** [comment]
yes, that would be helpful -->  also, on which OS are you?

**Comment by shruti927** [comment]
1. I installed Python 3.4.
2. I downloaded the mediawiki-utilities folder from https://github.com/mediawiki-utilities/python-mediawiki-utilities.
3. I wrote the following command in cmd to install mediawiki-utilities:
   C:/Python34/Scripts/pip install mediawiki-utilities
4. I downloaded wikiwho folder from https://github.com/maribelacosta/wikiwho/tree/python3 and ran the WikiwhoRelationships.py and first I got the following error and the new one in screnshot
   ![screenshot 2015-09-25 16 53 07](https://cloud.githubusercontent.com/assets/5814476/10099288/e682840e-63a5-11e5-9fee-3df9861ade5a.png)
   :
   File "C:\Python34\WikiwhoRelationships.py", line 14, in 
   from structures import Text
   ImportError: No module named 'structures'
   ![screenshot 2015-09-25 16 37 09](https://cloud.githubusercontent.com/assets/5814476/10099174/b986c9e8-63a4-11e5-8022-2daa29d9ae83.png)

**Comment by wikiwho** [comment]
hi, sorry for the late response.
-  I now tried it on windows(7) as well and using the python3 branch with the up-to-date mw-utlitites with python3.4.3 or 3.5 indeed throws errors coming from mw-utilities that do not appear on unix OSs apparently. so if you strictly want to use the python3 version (and Win) please ask aaron halfaker about those issues (or 0nsen who ported to python3, but he uses only Linux afaik). 
- the “structures”-not-found error (which would be usually the folder missing) never occured for me nor anyone i know that used wikiwho so far. if you just unzip the master-branch package i don’t see how that can happen.
- anyway, as the easiest solution: the master branch with python2.7 and the old bitbucket-version of mw-utilities runs fine for me on Win7. so i just recommend using that one.

**Comment by wikiwho** [comment]
on addition: I just saw "File "C:\Python34\WikiwhoRelationships.py", line 14, in from structures import Text ImportError: No module named 'structures' " -->  Did you copy just the WikiwhoRelationships.py in the Python34 folder without the rest of the folders and try to run it?
