### ISSUE TITLE
Pulling XML dumps

### ISSUE THREAD

**Issue by priyankamandikal** [maribelacosta/wikiwho#9]
Hi!
I am working on extending your project to include extracting revision dates of the content in a wiki article. I wanted to know from where I can get the xml dump of wiki articles. Currently I ran your code on this: https://en.wikipedia.org/wiki/Special:Export/Train
But it doesn't look like the complete xml dump to me. If you could suggest how I can get the xml dump of any article I want, it would be great

Thanks
Priyanka

**Comment by ErikBorra** [comment]
Hi @priyankamandikal,

have a look at http://dumps.wikimedia.org/enwiki/

Best,

Erik

**Comment by priyankamandikal** [comment]
Thanks @ErikBorra . That link gives me the xml dump of a lot of articles. Is there any way I can get the dump of an article of my choice?

Also, @maribelacosta , why did you choose to work with xml dumps and not use the api itself?
http://pythonhosted.org/mediawiki-utilities/core/api.html#mw.api.Revisions

Wouldn't this give the same result with fewer lines of code? I haven't gone through the entire code. I am just trying to understand the functions as of now. This was a question that popped up in my mind.

**Comment by wikiwho** [comment]
hi @priyankamandikal  (and waving @ErikBorra :) 
so two methods to get single article revision data:
1. a call to the WP API getting the revisions of an article including the content. doc here:
https://www.mediawiki.org/wiki/API:Revisions 
you need to ask for "content", and use "continue" for follow up calls, as you will get only 50 revisions per call in that way 
e.g., first query: https://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles=Mainz&rvprop=timestamp%7Cuser%7Ccomment%7Ccontent&format=json&continue (gives you back a continue value from where you can start your next query in the loop)
2. https://en.wikipedia.org/wiki/Special:Export/Somearticle (yet, the ordering of revisions and behavior of this is sometimes strange, so not recommended, although you can get more revisions at once) 

as for using the dump instead of the api: a) once downloaded, processing the dump is considerably faster than querying the api for each single article, b) we try to not put more load on the api than necessary. so if for example you would have to rerun something or testing it's better to do it on locally stored data.  however, we implemented an API for wikiwho that gets the the revisions needed from the WP API and iteratively updates them. I could either make that code public (have to check it first) or you can use the  precomputed results from our API (see here: http://f-squared.org/wikiwho/#api) – then you could simply query the WP API for the dates of the revisions that you get back from our API. 

Gruß, 
Fabian
